theme = "hugo-theme-blueberry-detox"
title='aw.stats'
baseurl = "https://austinwehrwein.com/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
ignoreErrors = ["error-remote-getjson"]
    # Loading min files for exampleSite
    customCSS            = ["/css/main.css"]
    customCSSP            = ["/css/prism.css"]


# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar

[social]
  
[Params]
    intro = true
    headline = "Austin Wehrwein"
    description = "Sporadic Data Analysis & Occasional Visualizations with R"
    github = "https://github.com/awhstin"
    linkedin = "https://linkedin.com/in/jaustinwehrwein"
    twitter = "https://twitter.com/awhstin"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    disqusShortname = "austinwehrwein"
    google_analytics = "UA-75498340-2"
    paginate = 1
